# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GalleryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GalleryApp
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.7.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'Hero'	
end
